### ISSUE TITLE
The polyfill reports intersections for elements set to `display: none`

### ISSUE THREAD

**Issue by philipwalton** [WICG/IntersectionObserver#145]
Externally reported here: https://github.com/Financial-Times/polyfill-service/issues/776

An easy fix would be to ignore `display: none` elements, but I'm wondering if spec clarification is needed here. Do we also need to consider how we handle intersecting but otherwise invisible elements (e.g. `opacity: 0` or `visibility: hidden`)?

Note that this is happening in the polyfill because a `display: none` element will report a `(0, 0, 0, 0)` rect, which (if it were visible) _would_ be considered an intersection as discussed in #69.

**Comment by ojanvafai** [comment]
display:none is special in that the element doesn't render at all.

opacity:0 and visibility:hidden make sense to do as part of v2 since they don't affect the size/position of an element, just whether it paints. So they are more similar to dealing with occlusion as we plan to in v2.

**Comment by rjgotten** [comment]
> Note that this is happening in the polyfill because a display: none element will report a (0, 0, 0, 0) rect, which (if it were visible) would be considered an intersection as discussed in #69.

The easiest way to fix that is to run an additional test based on `getClientRects()`, as that function will return an empty array for a `display: none` element.

Infact; you would also squash Internet Explorer related issues with that fix, because IE will throw an error on `getBoundingClientRect()` when called on a detached element, whereas `getClientRects()` won't and will *also* return an empty array for a detached element.

So:

```js
function getBoundingClientRect(el) {
  // Filter out `display:none` and detached elements
  if (!el.getClientRects().length) return;

  var rect = el.getBoundingClientRect();

  // Older IE
  if (!rect.width || !rect.height) {
    rect = {
      top: rect.top,
      right: rect.right,
      bottom: rect.bottom,
      left: rect.left,
      width: rect.right - rect.left,
      height: rect.bottom - rect.top
    };
  }
  return rect;
}
```
