### ISSUE TITLE
Expose IntersectionObserver as a ponyfill

### ISSUE THREAD

**Issue by rasmusfl0e** [WICG/IntersectionObserver#226]
Would it be possible to expose IntersectionObserver as a ponyfill?

**Comment by philipwalton** [comment]
I don't think that it makes sense in this case. Especially since in some situations (like Edge), only part of the native implementation is missing, so the polyfill only adds a small amount of code and depends on the native implementation for the rest. This is far better for performance than a ponyfill would be.

Also, since this polyfill is being built in conjunction with the spec, a lot of the arguments for ponyfills over polyfills don't apply here.

**Comment by rasmusfl0e** [comment]
I can appreciate that. I hadn't realized that it also did partial polyfilling :)

Thanks for quick reply - I'll close the issue.

**Comment by rasmusfl0e** [comment]
FWIW I made a ponyfill by repackaging the polyfill (transformed with babel; add export, remove IIFE/global exposure): https://github.com/rasmusfl0e/inteobs

I guess it should be able to handle most updates the polyfill gets :)
