### ISSUE TITLE
What happens when an observation is started for a target which is already intersecting?

### ISSUE THREAD

**Issue by mpb** [WICG/IntersectionObserver#73]
My suggestion: since the previous intersection rect is currently `null` for this observer/target pair, the next layout step should see that the new intersection is different and enqueue a callback at that point in time. This keeps us from requiring a layout at the time `observer.observe()` is called, and the only gap would be if *nothing* happens on the main thread after the observation is started.

**Comment by ojanvafai** [comment]
LGTM

**Comment by mpb** [comment]
Followup observations:
1) This works regardless of if the target was previously being observed, since the previous intersection rect is stored 'per observer/target pair'
2) We should probably call the target 'dirty' and mark that it needs a re-layout, otherwise app developers will intentionally make a change to force layout, since that's the only way to guarantee the callback gets triggered.
Thoughts?

**Comment by tabatkins** [comment]
Agree that firing the callback in the next frame makes sense.  No need to do it immediately, but there is need to do it.

Also agree that the target should definitely do a re-layout asap, so you get dependable callback firing.

**Comment by ojanvafai** [comment]
Discussed in person. Don't want to force the whole rendering pipeline to run if nothing changed. Instead, will post a task to run just the IO update steps.

This has a slight downside of making it so that we might run the update steps twice in the rare case where observe is called, then the task fires, then the dom is modified, then the rendering steps run. Maybe that's OK?

In an ideal world, we could say that we'd post the task only if a new rendering frame isn't scheduled, but we're unsure if there's a way to say that in the specs.

**Comment by tabatkins** [comment]
That should be possible, actually.  Put together some generic language about it not posting if it's about to be posted anyway, and then give the specific example of our rendering frames.

**Comment by ojanvafai** [comment]
esprehn says we should just schedule a frame. but it's cheap since no layout is dirty.

**Comment by ojanvafai** [comment]
And that it's very rare to observe without changing anything in the page that schedules a frame.
